services:
  ebank-discovery-service:
    build:
      context: discovery-service
    #image: discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http\\:localhost:87611/actuator/health"]
      interval: 10s