services:
  ebank-discovery-service:
    build:
      context: discovery-service
    #image: discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http\\:localhost:87611/actuator/health"]
      interval: 10s

  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - '8889:8889'
    expose:
      - '8889'