services:
  ebank-discovery-service:
    build:
      context: discovery-service
    #image: discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s

  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - '8889:8889'
    expose:
      - '8889'
    environment:
      - DISCOVERY_SERVICE_URL:http://ebank-discovery-service:8761/eureka
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
